# This file was generated by GoReleaser. DO NOT EDIT.
cask "run" do
  version "0.27.0"

  on_macos do
    on_arm do
      sha256 "4833f028894d9428b4910f9a97ae660795392f3436d06f5916e1c539af8c0ad6"
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "84c690d04afb5e6d1ea5d3c6b62eb921c96a369a0d12b1df48e272820420c426"
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0c9f8e0e44af3adf8ac1a75cd712a4448ea8e57e2fee326f205b0492fff28bac"
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "781bf3b9234c465a86195d614611d236eeea9cd2e309d6ad27c95c0f7991e131"
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Linux_x86_64.tar.gz"
    end
  end

  name "run"
  desc "Run CLI is an interactive CLI to manage your Google Cloud Run resources with panache!"
  homepage "https://github.com/JulienBreux/run-cli/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "run"

  # No zap stanza required
end
