# This file was generated by GoReleaser. DO NOT EDIT.
cask "run" do
  name "run"
  desc "Run CLI is an interactive CLI to manage your Google Cloud Run resources with panache!"
  homepage "https://github.com/JulienBreux/run-cli/"
  version "0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "run"

  on_macos do
    on_intel do
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Darwin_x86_64.tar.gz"
      sha256 "f0a83eafcaefc18ae1b39f7057822a36a7336f72d96dc127df2a3bd1830c5419"
    end
    on_arm do
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Darwin_arm64.tar.gz"
      sha256 "d9c96b2b1964499aa5ac516695dd39c57dff40e15c5a5177e96875abcd74e7a4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Linux_x86_64.tar.gz"
      sha256 "46c92ada12c146ea7aeae605279391f21ce91e884efb283b39c0c2b03da1dc70"
    end
    on_arm do
      url "https://github.com/JulienBreux/run-cli/releases/download/v#{version}/run_Linux_arm64.tar.gz"
      sha256 "12b191985f28b00022cd8e03b4dfd3b3df743623ae5ea7b717d721b7a56a8bf5"
    end
  end

  # No zap stanza required
end
